### ISSUE TITLE
Add concurrent sorting

### ISSUE THREAD

**Issue by yonderblue** [bsm/extsort#3]
Would be a great feature since it is very sort bound currently. Otherwise works well! 👍

**Comment by dim** [comment]
My original implementation https://github.com/bsm/streamsort used to support an [iterative](https://en.wikipedia.org/wiki/K-way_merge_algorithm#Iterative_2-Way_merge) approach with multiple go-routines. This newer implementation uses a heap-based [direct](https://en.wikipedia.org/wiki/K-way_merge_algorithm#Direct_k-way_merge) method instead. From my (limited) benchmarks it achieves a similar sort performance but in a single thread, but I would happily accept a PR if you think there's an opportunity for optimisation here :)

**Comment by dim** [comment]
Implemented in #8
